### ISSUE TITLE
CLuaEmitter Error on remove

### ISSUE THREAD

**Issue by Samg381** [weltensturm/wac#113]
I'm getting an error each time a WAC Helicopter is deleted on my server.
I've tried re-installing the addon, and uninstalling addons one by one etc.. but the error persists.

[ERROR] addons/wac aircraft/lua/entities/wac_hc_base/cl_init.lua:182: Tried to use invalid object (type CLuaEmitter) (Object was NULL or not of the right type)
  1. Finish - [C]:-1
   2. unknown - addons/wac aircraft/lua/entities/wac_hc_base/cl_init.lua:182

code in question:

function ENT:OnRemove()
	for _,s in pairs(self.sounds) do
		s:Stop()
	end
	for _, t in pairs(self.weaponAttachments) do
		t.model:Remove()
	end
	self.Emitter:Finish()
end

**Comment by MattJeanes** [comment]
I've fixed this error in #112. Waiting on merge

**Comment by Samg381** [comment]
Still getting some persistent errors after changing what #112 addressed. Will post them as they apear standby.

**Comment by Samg381** [comment]
[ERROR] addons/wac aircraft/lua/entities/wac_hc_base/cl_init.lua:605: 'end' expected (to close 'function' at line 159) near '<eof>'
  1. unknown - addons/wac aircraft/lua/entities/wac_hc_base/cl_init.lua:0

**Comment by Samg381** [comment]
[ERROR] addons/wac aircraft/lua/entities/wac_hc_base/cl_init.lua:182: attempt to index global 'ENT' (a nil value)
  1. attachmentThink - addons/wac aircraft/lua/entities/wac_hc_base/cl_init.lua:182
   2. unknown - addons/wac aircraft/lua/entities/wac_hc_base/cl_init.lua:85

**Comment by Samg381** [comment]
Thanks, updated and all is well.
